project:
  type: website

website:
  title: "Gaston.jl"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: tutorial.qmd
        text: Tutorial
      - href: examples.qmd
        text: Examples
      - href: recipes.qmd
        text: Recipes
      - href: manual.qmd
        text: Manual
      - href: reference.qmd
        text: API Reference
    tools:
      - icon: github
        href: https://github.com/mbaz/Gaston.jl
    search: true
    pinned: true
    reader-mode: true
    back-to-top-navigation: true

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true
    embed-resources: true

engines: ['julia']

execute:
  daemon: 600

filters:
  - code-visibility


