name: CI

on:
  pull_request:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  julia-lts:
    name: Julia LTS
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install gnuplot
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.10
          arch: x64
      - uses: actions/checkout@v3
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest

  julia-stable:
    name: Julia Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install gnuplot
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
          arch: x64
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
